# config/_default/languagues.zh.toml

languageCode = "zh-cn"
languageName = "Chinese-Simplified"
displayName = "中文"
htmlCode = "zh-cn"
weight = 1
rtl = false
title = "桔仔的博客"
copyright = "&copy; 2023 Spike"

[params]
  isoCode = "zh-cn"
  displayName = "中文"
  rtl = false

  dateFormat = "2 January 2006"

  mainSections = ["500-Blogs"]
  description = "Spike 的博客"


# Language-specific parameters go here
[author]
  name = "Spike"
  image = "/icons/avatar.png"
  headline = ""
  bio = "hello"
  links = [
    { github = "https://github.com/silentbluedrop/" },
    { twitter = "https://twitter.com/bluedrop9" },
  ]