# config/_default/languagues.zh.toml

languageCode = "zh-cn"
languageName = "Chinese-Simplified"
displayName = "中文"
htmlCode = "zh-cn"
weight = 1
rtl = false
title = "🍊桔仔的博客"
copyright = "&copy; 2024 桔仔"

[params]
  isoCode = "zh-cn"
  displayName = "中文"
  rtl = false

  dateFormat = "2 January 2006"

  mainSections = ["500-Blogs"]
  description = "桔仔的博客"


# Language-specific parameters go here
[author]
  name = " 桔仔  • GatZai"
  image = "/imgs/avatar.png"
  headline = "记录产生美好"
  bio = "记录产生美好"
  links = [
    { github = "https://github.com/gatzai/" },
    { twitter = "https://twitter.com/bluedrop9" },
    { instagram = "https://www.instagram.com/bluedrop8/" },
    { telegram = "https://t.me/primalwildness"},
    { itch = "https://itch.io/dashboard"},
    { email = "2899561390@qq.com"},
  ]
