languageCode = "zh-cn"
languageName = "Chinese"
displayName = "简中"
isoCode = "cn"
weight = 1
rtl = false

title = "🍊桔仔的博客"
# logo = "img/logo.png"
description = "你好"
copyright = "Copyright © 2023 Primalwildness"

dateFormat = "2 January 2006"

[author]
name = "桔仔"
image = "img/avatar.png"
headline = "---"
bio = "今天也很棒"
  links = [
		{ email = "2899561390@qq.com" },
		{ github = "https://github.com/silentbluedrop" },
	  { twitter = "https://twitter.com/bluedrop9" },
	  { steam = "https://steamcommunity.com/profiles/76561198209363303" },
		{ telegram = "https://t.me/primalwildness" },
#     { link = "https://link-to-some-website.com/" },
#     { amazon = "https://www.amazon.com/hz/wishlist/ls/wishlist-id" },
#     { apple = "https://www.apple.com" },
#     { blogger = "https://username.blogspot.com/" },
#     { codepen = "https://codepen.io/username" },
#     { dev = "https://dev.to/username" },
#     { discord = "https://discord.gg/invitecode" },
#     { dribbble = "https://dribbble.com/username" },
#     { facebook = "https://facebook.com/username" },
#     { flickr = "https://www.flickr.com/photos/username/" },
#     { foursquare = "https://foursquare.com/username" },
#     { gitlab = "https://gitlab.com/username" },
#     { google = "https://www.google.com/" },
#     { hashnode = "https://username.hashnode.dev" },
#     { instagram = "https://instagram.com/username" },
#     { keybase = "https://keybase.io/username" },
#     { kickstarter = "https://www.kickstarter.com/profile/username" },
#     { lastfm = "https://lastfm.com/user/username" },
#     { linkedin = "https://linkedin.com/in/username" },
#     { mastodon = "https://mastodon.instance/@username" },
#     { medium = "https://medium.com/username" },
#     { microsoft = "https://www.microsoft.com/" },
#     { orcid = "https://orcid.org/userid" },
#     { patreon = "https://www.patreon.com/username" },
#     { pinterest = "https://pinterest.com/username" },
#     { reddit = "https://reddit.com/user/username" },
#     { researchgate = "https://www.researchgate.net/profile/username" },
#     { slack = "https://workspace.url/team/userid" },
#     { snapchat = "https://snapchat.com/add/username" },
#     { soundcloud = "https://soundcloud.com/username" },
#     { stack-overflow = "https://stackoverflow.com/users/userid/username" },
#     { tiktok = "https://tiktok.com/@username" },
#     { tumblr = "https://username.tumblr.com" },
#     { twitch = "https://twitch.tv/username" },
#     { whatsapp = "https://wa.me/phone-number" },
#     { youtube = "https://youtube.com/username" },
#     { ko-fi = "https://ko-fi.com/username" },
  ]
